name: CI/CD - Retail Banking

on:
  push:
    branches:
      - master   # or main depending on your repo default
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Unit Tests
        run: mvn test

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: retail-banking-jar
          path: target/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/retail-banking:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: SSH to Server & Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/retail-banking || git clone https://github.com/ohbus/retail-banking.git ~/retail-banking
            cd ~/retail-banking
            git pull origin master
            docker pull ${{ secrets.DOCKER_USERNAME }}/retail-banking:latest
            docker compose -f docker-compose.prod.yml up -d --build
